// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehxqffqmsqkhzvwkfjjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoeHFmZnFtc3FraHp2d2tmampyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3MjMyMTMsImV4cCI6MjA4NzI5OTIxM30.7TE0o3pZSiXISI8BkFG-o7p_acM_rM4_qTqrPxduVBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});